language: java
before_install:
  - git clone -b Develop https://github.com/sunyifan112358/pvis.git sunyifan112358/pvis
script: mvn test
after_success:
  - mvn clean test jacoco:report coveralls:report
jdk:
  - oraclejdk8